server:
  port: 8001
mybatis:
  type-aliases-package: com.ghh.api.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: root