server:
  port: 9527

spring:
  application:
    name: micorservicecloud-zuul-gateway

eureka:
  client:  #服务注册尽eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com  #自定义eureka上显示的名称
    prefer-ip-address: true  # 访问路径可以显示IP地址
info:
  app.name: microservicecloud-provider-dept-8001
  company.name: ghh
  build.artifactId: @project.artifactId@           # 显示当前项目的名称以及
  build.version: @project.version@


#zuul的地址映射规则
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept  # 真实微服务的名称  映射之前：http://myzuul.com:9527/microservicecloud-dept/findAll
    mydept.path: /mydept/**          # 映射之后的名称  http://myzuul.com:9527/mydept/findAll

#  ignored-services: microservicecloud-dept # 禁止单个的微服务真实路由访问
  ignored-services: "*"   # 禁止所有微服务真实路由访问
  prefix: /ghh     # 所有微服务路由前加上的前缀